### ISSUE TITLE
QObject::moveToThread:

### ISSUE THREAD

**Issue by Arise12** [Gaussian-Splatting-Toolkit/Gaussian-Splatting-Toolkit#2]
Hello, Thanks for this great work
I have encountered some problems when I run this code on a remote server. 

gs-process-data images --data Gaussian-Splatting-Toolkit/data --output-dir Gaussian-Splatting-Toolkit/output

![屏幕截图 2024-04-23 165336](https://github.com/Gaussian-Splatting-Toolkit/Gaussian-Splatting-Toolkit/assets/52425753/f18da08f-46cd-4614-911e-b08396ab1006)

So could you please give some recommends to solve this problem? Thank you very much

**Comment by H-tr** [comment]
Hi! I've replaced the camera pose estimation with hloc and set the default descriptor extractor and matcher as superpoint and superglue. It should not depend on the colmap now. Could you have a try? Please let me know if there are any further issue.
