### ISSUE TITLE
Use Colmap

### ISSUE THREAD

**Issue by Arise12** [Gaussian-Splatting-Toolkit/Gaussian-Splatting-Toolkit#3]
HLOC用起来太慢了，希望能恢复使用colmap作为一个·可选项

**Comment by H-tr** [comment]
May I know which part is slow? The Feature extraction, matching, or bundle adjustment?

If the bottleneck is the feature extraction, you can just add `--feature-type sift` and it would be the same with colmap. HLOC shares the same bundle adjustment pipeline with colmap.

If the main time usage comes from feature matching in your case, I'll try to restore the colmap.
